name: Trigger PIAS Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - infra/**
      - ".github/workflows/infra.yml"

jobs:
  SANDBOX:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Invoke PIAS workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: infra
          repo: IEA-Paris/PIAS
          token: ${{ secrets.SERVICE_USER_PAT }}
          ref: refs/heads/main
          inputs: '{ "name": "SANDBOX", "domain": "sandbox", "acm_certificate_arn": "arn:aws:acm:eu-west-3:720928668014:certificate/b996697b-4632-4080-8b4b-729d05a9303f"}'
